DefaultContentLanguage = "en"
# baseURL = "https://donnisnoni.github.io/"
baseURL = "http://localhost:8080/"
languageCode = "en"
title = "Don Alfons Nisnoni"

[params]
author = "Don Alfons Nisnoni"

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[build]
writeStats = true
