DefaultContentLanguage = "en"
baseURL = "https://donnisnoni.github.io/"
languageCode = "en"
title = "Don Nisnoni's Blog"

[params]
author = "Don Alfons Nisnoni"
twitter_username = "AlfonsDon"

[taxonomies]
tag = "tags"

[build]
writeStats = true

[markup]
[markup.highlight]
noClasses = false
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true
